[project]
name = "faceoff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "insightface>=0.7.3",
    "onnxruntime>=1.16,<1.20",
    "opencv-python>=4.12.0.88",
]
